# Generated by Django 3.2.11 on 2022-01-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_followrequests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='followers',
            new_name='friends',
        ),
    ]
