version: "3"
services:
  db:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=social_network
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:var/lib/postgresql/data