# Generated by Django 3.2.11 on 2022-01-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='visibility',
            field=models.CharField(blank=True, choices=[('PUB', 'Public'), ('PRO', 'Protected'), ('PRI', 'Private')], default='PUB', max_length=3),
        ),
    ]
