# Generated by Django 3.2.11 on 2022-01-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_feed_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRO', 'Protected'), ('PRI', 'Private')], default='PRI', max_length=3),
        ),
    ]
